# --- Constantes da Missão ---
ALTITUDE_DE_BUSCA = 2.5
PASSO_DA_VARREDURA = 1.0   
VEL_LATERAL = 1.0          
VEL_FRENTE = 1.0           

# --- Definição dos Estados ---
ESTADO_INICIANDO = "INICIANDO"
ESTADO_ARMANDO = "ARMANDO"
ESTADO_DECOLANDO = "DECOLANDO"
ESTADO_BUSCANDO = "BUSCANDO"
ESTADO_CENTRALIZANDO = "CENTRALIZANDO"
ESTADO_POUSANDO_ALVO = "POUSANDO_ALVO"
ESTADO_RE_ARMANDO = "RE_ARMANDO"
ESTADO_RE_DECOLANDO = "RE_DECOLANDO"
ESTADO_RETORNANDO_RTL = "RETORNANDO_RTL"
ESTADO_FALHA_CRITICA = "FALHA_CRITICA"
ESTADO_FINALIZADO = "FINALIZADO"