import cv2 as cv 
# CONFIGURAÇÕES GERAIS DA APLICAÇÃO

# -- CONFIGURAÇÕES DA CÂMERA --
CAMERA_INDEX = 0
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720

# -- PARÂMETROS DE DETECÇÃO --
MIN_CONTOUR_AREA = 400
CANNY_THRESHOLD_1 = 50
CANNY_THRESHOLD_2 = 150
APPROX_POLY_FACTOR = 0.02 # Fator para o cv2.approxPolyDP

# -- PARÂMETROS DE DESENHO --
FONT = cv.FONT_HERSHEY_SIMPLEX
FONT_SCALE = 0.7
FONT_THICKNESS = 2
CONTOUR_COLOR = (0, 255, 0)
CONTOUR_THICKNESS = 3